const sampleProducts = [
  {
    name: '100% Organic Comb Cotton Single Jersey',
    description: 'Ultra-soft, breathable combed organic cotton knit. Ideal for premium t-shirts, loungewear, and baby apparel.',
    category: 'Sustainable',
    fabricType: 'Organic Cotton',
    price: 4.80,
    unit: 'meter',
    stock: 12500,
    moq: 200,
    colors: ['Off-White', 'Navy Blue', 'Olive Green', 'Jet Black'],
    images: ['https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 180, widthInches: 60, pattern: 'Solid', origin: 'India' },
    isFeatured: true,
  },
  {
    name: 'Raw Heavyweight Indigo Denim (14oz)',
    description: 'Durable 100% cotton selvedge denim fabric. Unwashed indigo dye perfect for jeans, jackets, and workwear.',
    category: 'Denim',
    fabricType: 'Cotton Denim',
    price: 6.50,
    unit: 'meter',
    stock: 8000,
    moq: 500,
    colors: ['Deep Indigo', 'Raw Black'],
    images: ['https://images.unsplash.com/photo-1542272604-780c96856592?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 420, widthInches: 58, pattern: 'Twill 3/1', origin: 'Turkey' },
    isFeatured: true,
  },
  {
    name: 'Pure Mulberry Silk Charmeuse Satin',
    description: 'High-luster, luxurious 19 momme Mulberry silk fabric. Silky texture for evening gowns, scarves, and luxury bedding.',
    category: 'Silk & Wool',
    fabricType: 'Mulberry Silk',
    price: 18.50,
    unit: 'meter',
    stock: 3200,
    moq: 50,
    colors: ['Champagne', 'Ruby Red', 'Emerald', 'Pearl White'],
    images: ['https://images.unsplash.com/photo-1606813907291-d86efa9b94db?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 85, widthInches: 44, pattern: 'Satin Weave', origin: 'China' },
    isFeatured: true,
  },
  {
    name: 'Pure Belgian Linen Slub Plain Weave',
    description: 'Natural slub texture Belgian flax linen. Highly breathable and durable for summer shirts, dresses, and home drapes.',
    category: 'Woven',
    fabricType: 'Pure Linen',
    price: 9.20,
    unit: 'meter',
    stock: 6500,
    moq: 150,
    colors: ['Natural Oat', 'Sand Beige', 'Soft Ochre', 'Sage'],
    images: ['https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 210, widthInches: 56, pattern: 'Plain Slub', origin: 'Belgium' },
    isFeatured: false,
  },
  {
    name: 'Ripstop Cordura Waterproof Nylon (500D)',
    description: 'High-tenacity technical nylon fabric with PU backing. Water-resistant and tear-proof for tactical gear, backpacks, and outdoor outerwear.',
    category: 'Synthetic',
    fabricType: 'Technical Nylon',
    price: 7.90,
    unit: 'meter',
    stock: 15000,
    moq: 300,
    colors: ['Coyote Brown', 'Tactical Black', 'Forest Camo'],
    images: ['https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 260, widthInches: 60, pattern: 'Ripstop Weave', origin: 'South Korea' },
    isFeatured: true,
  },
  {
    name: 'Fine Australian Merino Wool Suiting',
    description: 'Super 120s combed Australian Merino wool suiting weave. Wrinkle-resistant drape for tailored suits, blazers, and trousers.',
    category: 'Silk & Wool',
    fabricType: 'Merino Wool',
    price: 24.00,
    unit: 'meter',
    stock: 2400,
    moq: 100,
    colors: ['Charcoal Grey', 'Midnight Blue', 'Black Pin-stripe'],
    images: ['https://images.unsplash.com/photo-1617325247661-675ab4b64ae2?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 280, widthInches: 58, pattern: 'Hertingbone', origin: 'Australia' },
    isFeatured: false,
  },
  {
    name: 'Recycled Poly-Spandex Activewear Knit',
    description: '4-way stretch moisture-wicking interlock knit fabric made from 82% rPET polyester and 18% Elastane. Designed for leggings and sportswear.',
    category: 'Sustainable',
    fabricType: 'Recycled Poly-Spandex',
    price: 5.40,
    unit: 'meter',
    stock: 18000,
    moq: 250,
    colors: ['Matte Black', 'Electric Blue', 'Coral Pink', 'Steel Grey'],
    images: ['https://images.unsplash.com/photo-1518609878373-06d740f60d8b?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 240, widthInches: 60, pattern: 'Matte Interlock', origin: 'Vietnam' },
    isFeatured: true,
  },
  {
    name: 'Digital Printed Floral Rayon Viscose',
    description: 'Flowy, lightweight printed viscose rayon with vibrant color fastness. Perfect for resort wear, blouses, and dresses.',
    category: 'Custom Print',
    fabricType: 'Rayon Viscose',
    price: 3.90,
    unit: 'meter',
    stock: 9500,
    moq: 100,
    colors: ['Botanical Floral', 'Tropical Palm', 'Abstract Navy'],
    images: ['https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?w=800&auto=format&fit=crop&q=80'],
    specifications: { weightGSM: 130, widthInches: 54, pattern: 'Reactive Digital Print', origin: 'India' },
    isFeatured: false,
  },
];

module.exports = sampleProducts;
